/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graph.plotter;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *This class is the main class of the project from here every activity starts
 * @author Dhruba
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    public static Menu M;
    public static javax.swing.JPanel menuPanel;
    public Menu() {
        initComponents();
        menuPanel =jPanel4;     /**Copying Panel*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barButton = new javax.swing.JButton();
        pieButton = new javax.swing.JButton();
        lineButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(700, 400));

        jPanel5.setLayout(null);

        jLabel4.setText("jLabel3");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(260, 10, 300, 180);

        jLabel5.setFont(new java.awt.Font("Rosewood Std Regular", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(12, 12, 69));
        jLabel5.setText("Graph Plotter");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(230, 170, 480, 80);

        jLabel6.setText("jLabel1");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(0, 0, 860, 510);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147, 2000));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));

        jPanel4.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel4.setLayout(null);

        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(260, 10, 300, 180);

        jLabel2.setFont(new java.awt.Font("Rosewood Std Regular", 3, 48)); // NOI18N
        jLabel2.setText("Graph Plotter");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(250, 180, 480, 80);

        barButton.setText("Bar Chart");
        barButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barButtonActionPerformed(evt);
            }
        });
        jPanel4.add(barButton);
        barButton.setBounds(120, 360, 90, 40);

        pieButton.setText("Pie Chart");
        pieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieButtonActionPerformed(evt);
            }
        });
        jPanel4.add(pieButton);
        pieButton.setBounds(390, 360, 90, 40);

        lineButton.setText("Line Graph");
        lineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineButtonActionPerformed(evt);
            }
        });
        jPanel4.add(lineButton);
        lineButton.setBounds(670, 360, 100, 40);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(exitButton);
        exitButton.setBounds(760, 100, 80, 40);

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        jPanel4.add(aboutButton);
        aboutButton.setBounds(760, 40, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graph/plotter/Background25.png"))); // NOI18N
        jLabel1.setText("Exit");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 500);

        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(690, 274, 40, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /***
     * This method clears main menu's panel and revalidate BarMenu panel
     * @param evt This is a ActionEvent Type event
     */
   
    private void barButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barButtonActionPerformed
        /**Transferring Panel to BarMenu**/
        
        Menu.M.getContentPane().removeAll();
        BarMenu B = new BarMenu();
        Menu.M.getContentPane().add(B.baMenurPanel);
        Menu.M.repaint();
        Menu.M.revalidate();
        //bm.setSize(858,513);
        //bm.setVisible(true);
    }//GEN-LAST:event_barButtonActionPerformed
    /***
     * This method clears main menu's panel and revalidate PieMenu Panel
     * @param evt This is a ActionEvent Type event
     */
    private void pieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieButtonActionPerformed
        /**Transferring Panel to PieMenu**/
        
        Menu.M.getContentPane().removeAll();
        PieMenu pm =new PieMenu();
        Menu.M.getContentPane().add(pm.piePanel);
        Menu.M.repaint();
        Menu.M.revalidate();
        
    }//GEN-LAST:event_pieButtonActionPerformed
    /***
     * This method clears main menu's panel and revalidate LineGraph panel
     * @param evt This is a ActionEvent Type event
     */
    private void lineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineButtonActionPerformed
        /**Transferring Panel to LineGraph**/
          
        LineGraph ln =new LineGraph();
        Menu.M.getContentPane().removeAll();
        
        Menu.M.getContentPane().add(ln.jPanel2);
        Menu.M.repaint();
        Menu.M.revalidate();
       
    }//GEN-LAST:event_lineButtonActionPerformed
    /***
     * This method calls the close() method and exits the frame
     * @param evt This is a ActionEvent Type event
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        Menu menu =new Menu();
        menu.close();
    }//GEN-LAST:event_exitButtonActionPerformed
    /***
     * This method clears main menu's panel and revalidate About
     * @param evt This is a ActionEvent Type event
     */
    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        
        About abt =new About();
        Menu.M.getContentPane().removeAll();
        
        Menu.M.getContentPane().add(abt.jPanel2);
        Menu.M.repaint();
        Menu.M.revalidate();
    }//GEN-LAST:event_aboutButtonActionPerformed

    
   /*
    The main method which runs the whole software
     * .0     --------------------+@param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               M =  new Menu();
               M.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton barButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lineButton;
    private javax.swing.JButton pieButton;
    // End of variables declaration//GEN-END:variables
    /***
     * This method creates object of WindowEvent and works on window closing.
     * 
     */
    private void close() {
        WindowEvent c = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(c);
        //Work on Exit Button
    }
}
